### ISSUE TITLE
方便快速部署维护的文档

### ISSUE THREAD

**Issue by jackerzhou** [tongdun/td-redis-operator#1]
有响应的部署维护文档吗

**Comment by houseonline** [comment]
谢谢你提交和反馈issue！
比较抱歉，我们是前几天刚刚开源的第一个beta版本，有一些文档与功能还在逐渐完善中。
这里是我们写的wiki文档初稿：
https://github.com/tongdun/td-redis-operator/wiki
你可以看看

**Comment by houseonline** [comment]
另外，我们将在2021年12月下旬正式发布 v0.1.0版本！
新的v0.1.0版本，将提供多种完备的一键部署方案。到时候，你可以使用新的v0.1.0版本很方便的进行部署。
敬请关注。

**Comment by houseonline** [comment]
如果有兴趣的话，@gaoshengL 这边可以提供一些临时的部署方法

**Comment by houseonline** [comment]
另外，我们将在2021年12月下旬正式发布 v0.1.0版本！
新的v0.1.0版本，将提供多种完备的一键部署方案。到时候，你可以使用新的v0.1.0版本很方便的进行部署。
敬请关注。

**Comment by jackerzhou** [comment]
嗯 方便的话，大佬可以提供一些临时的部署方法

**Comment by houseonline** [comment]
你可以使用`helm`命令来部署：

```
$ helm repo add td-redis-operator https://tongdun.github.io/td-redis-operator/charts/td-redis-operator
$ helm repo update
$ helm install [RELEASE_NAME] td-redis-operator/td-redis-operator      
```

关于`helm`的部署过程详见 <a href="https://github.com/tongdun/td-redis-operator/wiki/Deploy-by-Helm"> Helm部署文档 </a>.

除了使用`helm`部署外，你也可以使用`kubectl`命令部署：

```
$ kubectl apply -f https://github.com/tongdun/td-redis-operator/tree/main/deploy/deploy.yaml     
$ kubectl apply -f https://github.com/tongdun/td-redis-operator/tree/main/cr/redis_cluster.yaml
$ kubectl apply -f https://github.com/tongdun/td-redis-operator/tree/main/cr/redis_standby.yaml
```

更多YAML文件详见<a href="https://github.com/tongdun/td-redis-operator/wiki/Deploy-by-YAML"> YAML部署文档 </a>.
