### ISSUE TITLE
二进制部署在物理主机上面可以不呀

### ISSUE THREAD

**Issue by showsmall** [tongdun/td-redis-operator#3]
二进制部署在物理主机上面可以不呀

**Comment by gaoshengL** [comment]
具体描述下？比如如何部署、部署环境

**Comment by showsmall** [comment]
就是我直接在虚拟机上面或者物理机上面用编译成功的二进制文件进行部署

**Comment by gaoshengL** [comment]
建议按照部署文档在k8s部署

**Comment by houseonline** [comment]
如果你是中文用户，可以扫码加入社区微信群，进一步沟通交流你的问题：

![20220117122546](https://user-images.githubusercontent.com/13775491/149707964-1600bbb8-1bf9-4ac5-926d-bcda7b36f086.jpg)

**Comment by houseonline** [comment]
已溝通真實需求。
暫時關閉issue。
