### ISSUE TITLE
redis访问咨询

### ISSUE THREAD

**Issue by dockerxu123** [tongdun/td-redis-operator#4]
假如外网访问具体ingress映射到哪个服务上，还有内部访问方式是servername+namespace.svc这种方式访问？

**Comment by dockerxu123** [comment]
还有能不能在cluster调度的时候加 nodeSelector指定特定环境调度？ 如果可以在哪个文件修改？operator 的我修改成功了，cluster的修改报错

**Comment by dockerxu123** [comment]
还有能不能在cluster调度的时候加 nodeSelector指定特定环境调度？ 如果可以在哪个文件修改？operator 的我修改成功了，cluster的修改报错

**Comment by gaoshengL** [comment]
1、外部的网络访问方式，需要具体的额外网络方案，这个项目中默认还是内部访问
2、可以考虑添加nodeSelector，最近会提供注意关注，另外资源创建后cluster的yaml修改亲和度应该也是可以的，可以具体贴下报错看下

**Comment by dockerxu123** [comment]
方便加一下微信？ 哈哈&nbsp; 我现在也在部署中 有一个备的pod一直起不来







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tongdun/td-redis-operator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 中午1:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tongdun/td-redis-operator] redis访问咨询 (Issue #4)





 
1、外部的网络访问方式，需要具体的额外网络方案，这个项目中默认还是内部访问
 2、可以考虑添加nodeSelector，最近会提供注意关注，另外资源创建后cluster的yaml修改亲和度应该也是可以的，可以具体贴下报错看下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by houseonline** [comment]
> 方便加一下微信？ 哈哈&nbsp; 我现在也在部署中 有一个备的pod一直起不来
> […](#)


如果你是中文用户，可以扫码加入社区微信群，进一步沟通交流你的问题：

![20220117122546](https://user-images.githubusercontent.com/13775491/149707964-1600bbb8-1bf9-4ac5-926d-bcda7b36f086.jpg)

**Comment by gaoshengL** [comment]
你说的主备方式么，是有一个pod会处于非ready状态，这是架构决定的，主备pod有是否为master状态的readniess探针，所以slave会一直处于非ready状态，只有切换后才会成为master角色提供流量，https://github.com/tongdun/td-redis-operator/wiki/Redis-Standby%E4%BA%A4%E4%BB%98%E4%BB%8B%E7%BB%8D

**Comment by dockerxu123** [comment]
感谢&nbsp; 了解&nbsp; 我加一下群


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tongdun/td-redis-operator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tongdun/td-redis-operator] redis访问咨询 (Issue #4)





 
你说的主备方式么，是有一个pod会处于非ready状态，这是架构决定的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dockerxu123** [comment]
了解&nbsp; 我加一下群 感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tongdun/td-redis-operator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tongdun/td-redis-operator] redis访问咨询 (Issue #4)





 
你说的主备方式么，是有一个pod会处于非ready状态，这是架构决定的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
