### ISSUE TITLE
请问下你们代理是自研的吗

### ISSUE THREAD

**Issue by ztbill** [tongdun/td-redis-operator#6]
请问下你们代理是自研的吗，是否有相关说明和部署文档

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by gaoshengL** [comment]
引用自https://github.com/joyieldInc/predixy，建议生产使用直连

**Comment by houseonline** [comment]
生產環境使用直連的話，比使用predixy代理的效能要好很多。
（1）如果你的用戶端不想直連，可以使用代理模式來進行，這樣比較省事。
（2）如果你追求極致的效能的話，建議還是使用直連。

**Comment by houseonline** [comment]
有興趣也可以加入我們的社區微信群進行溝通，掃描下麵的二維碼即可加入：

![td-redis-operator](https://raw.githubusercontent.com/tongdun/td-redis-operator/main/docs/imgs/wechatqrcode.jpg)
