### ISSUE TITLE
Is there any Docker file for reference?

### ISSUE THREAD

**Issue by IDerr** [tongdun/td-redis-operator#9]
Hello,

where can i find the docker images used in this project 
tongduncloud/redis-cluster for example 
And what's the difference between official images ?

Thanks a lot

**Comment by IDerr** [comment]
i didn't found anything in this repo :(

**Comment by gaoshengL** [comment]
hi,there is nearly no difference between officila images,we only add some script and binary file(you can find in pod instance) into docker iamges,just like:

Dockerfile of redis standby:
```
FROM registry.tongdun.me/library/centos7.2-common:1.1.0
RUN mkdir /home/admin/redis && \
    cd /home/admin/redis && \
    mkdir output data script
COPY redis-server redis-cli redis-check-rdb docker-entrypoint.sh check_ok.py  check_master.py  redis-login.sh /usr/local/bin/
COPY init_redis.py /home/admin/redis/script
ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 6379
```

Dockerfile of sentinel:
```
FROM registry.tongdun.me/library/centos7.2-common:1.1.0
RUN mkdir /home/admin/sentinel && \
    cd /home/admin/sentinel && \
    mkdir output && \
    mkdir script
COPY redis-cli redis-sentinel docker-entrypoint.sh  check_sentinel_alive.sh /usr/local/bin/
COPY sentinel.conf /home/admin/sentinel
COPY init_sentinel.py /home/admin/sentinel/script
ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 26379
```

**Comment by houseonline** [comment]
Here are some commonly used Dockerfile for your reference:

- https://github.com/tongdun/td-redis-operator/blob/main/Dockerfile/Redis-Sentinel.Dockerfile
- https://github.com/tongdun/td-redis-operator/blob/main/Dockerfile/Redis-Active_standby.Dockerfile

**Comment by IDerr** [comment]
Thanks for that
